import { Tooltip } from "@mui/material";

const LEVEL_THREE_COLUMNS = [
  {
    id: "",
    label: "",
    minWidth: "",
    sx: { border : "0.25px solid red"},
    colSpan: 1,
  },
  {
    id: "",
    label: "",
    minWidth: "",
    sx: { border : "0.25px solid red"},
    colSpan: 1,
  },
  {
    id: "",
    label: "",
    minWidth: "",
    sx: { border : "0.25px solid red"},
    colSpan: 1,
  },
  {
    id: "portfolio_50_percent",
    label: "50% portfolio",
    minWidth: "",
    sx: { border : "0.25px solid red"},
    colSpan: 1,
  },
  {
    id: "portfolio_25_percent",
    label: "25% portfolio",
    minWidth: "",
    sx: { border : "0.25px solid red"},
    colSpan: 1,
  },
  {
    id: "top_10_investor_percent",
    label: "Top 10 investor (%)",
    minWidth: "",
    sx: { border : "0.25px solid red"},
    colSpan: 1,
  },
  {
    id: "large_cap_percent",
    label: "Large Cap (%)",
    minWidth: "",
    sx: { border : "0.25px solid red"},
    colSpan: 1,
  },
  {
    id: "mid_cap_percent",
    label: "Mid Cap (%)",
    minWidth: "",
    sx: { border : "0.25px solid red"},
    colSpan: 1,
  },
  {
    id: "small_cap_percent",
    label: "Small Cap (%)",
    minWidth: "",
    sx: { border : "0.25px solid red"},
    colSpan: 1,
  },
  {
    id: "cash_percent",
    label: "Cash Percent (%)",
    minWidth: "",
    sx: { border : "0.25px solid red"},
    colSpan: 1,
  },
  {
    id: "",
    label: "",
    minWidth: "",
    sx: { border : "0.25px solid red"},
    colSpan: 1,
  },
  {
    id: "",
    label: "",
    minWidth: "",
    sx: { border : "0.25px solid red"},
    colSpan: 1,
  },
  {
    id: "",
    label: "",
    minWidth: "",
    sx: { border : "0.25px solid red"},
    colSpan: 1,
  },
  {
    id: "",
    label: "",
    minWidth: "",
    sx: { border : "0.25px solid red"},
    colSpan: 1,
  },
  {
    id: "trailing_12m_pe",
    label: "Trailing 12m PE",
    minWidth: "",
    sx: { border : "0.25px solid red"},
    colSpan: 1,
  },
  {
    id: "trailing_12m_pe_1yr_ago",
    label: "Trailing 12m PE 1 year ago",
    minWidth: "",
    sx: { border : "0.25px solid red"},
    colSpan: 1,
  },
  {
    id: "trailine_12m_pe_2yr_ago",
    label: "Trailing 12m PE 2 year ago",
    minWidth: "",
    sx: { border : "0.25px solid red"},
    colSpan: 1,
  },
  {
    id: "",
    label: "",
    minWidth: "",
    sx: { border : "0.25px solid red"},
    colSpan: 1,
  },
];

export { LEVEL_THREE_COLUMNS };
