const LEVEL_FOUR_COLUMS = [
  {
    id: "empty_one",
    label: "As of (Portfolio date)",
    minWidth: "",
    sx: {border : '0.25px solid red'},
    colSpan: 1,
  },
  {
    id: "empty_two",
    label: "Scheme Name",
    minWidth: "",
    sx: {border : '0.25px solid red'},
    colSpan: 1,
  },
  {
    id: "empty_three",
    label: "AUM (Rs. Cr)",
    minWidth: "",
    sx: {border : '0.25px solid red'},
    colSpan: 1,
  },
  {
    id: "a",
    label: "(A)",
    minWidth: "",
    sx: {border : '0.25px solid red'},
    colSpan: 1,
  },
  {
    id: "b",
    label: "(B)",
    minWidth: "",
    sx: {border : '0.25px solid red'},
    colSpan: 1,
  },
  {
    id: "c",
    label: "(C)",
    minWidth: "",
    sx: {border : '0.25px solid red'},
    colSpan: 1,
  },
  {
    id: "d",
    label: "(D)",
    minWidth: "",
    sx: {border : '0.25px solid red'},
    colSpan: 1,
  },
  {
    id: "e",
    label: "(E)",
    minWidth: "",
    sx: {border : '0.25px solid red'},
    colSpan: 1,
  },
  {
    id: "f",
    label: "(F)",
    minWidth: "",
    sx: {border : '0.25px solid red'},
    colSpan: 1,
  },
  {
    id: "g",
    label: "(G)",
    minWidth: "",
    sx: {border : '0.25px solid red'},
    colSpan: 1,
  },
  {
    id: "h",
    label: "(H)",
    minWidth: "",
    sx: {border : '0.25px solid red'},
    colSpan: 1,
  },
  {
    id: "i",
    label: "(I)",
    minWidth: "",
    sx: {border : '0.25px solid red'},
    colSpan: 1,
  },
  {
    id: "j",
    label: "(J)",
    minWidth: "",
    sx: {border : '0.25px solid red'},
    colSpan: 1,
  },
  {
    id: "k",
    label: "(K)",
    minWidth: "",
    sx: {border : '0.25px solid red'},
    colSpan: 1,
  },
  {
    id: "l",
    label: "(L)",
    minWidth: "",
    sx: {border : '0.25px solid red'},
    colSpan: 1,
  },
  {
    id: "m",
    label: "(M)",
    minWidth: "",
    sx: {border : '0.25px solid red'},
    colSpan: 1,
  },
  {
    id: "n",
    label: "(N)",
    minWidth: "",
    sx: {border : '0.25px solid red'},
    colSpan: 1,
  },
  {
    id: "o",
    label: "(O)",
    minWidth: "",
    sx: {border : '0.25px solid red'},
    colSpan: 1,
  },
];

export { LEVEL_FOUR_COLUMS };
